version: "3.3"

volumes:
  fastapi-training-db-data:

services:
  db:
    image: kartoza/postgis:15-3.3
    container_name: fastapi-training-db
    volumes:
      - fastapi-training-db-data:/var/lib/postgresql
    ports:
      - ${database_port}:5432
    environment:
      - POSTGRES_DB=${database_name}
      - POSTGRES_USER=${database_username}
      - POSTGRES_PASS=${database_password}
      - FORCE_SSL=FALSE
    restart: on-failure
  api:
    container_name: fastapi-training-api
    build: ./src
    command: |
      bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000'
    volumes:
      - ./src/:/usr/src/
    ports:
      - 8002:8000
