version: "3.3"

volumes:
  fastapi-training-db-data:

services:
  db:
    image: kartoza/postgis:15-3.3
    container_name: fastapi-training
    volumes:
      - fastapi-training-db-data:/var/lib/postgresql
    ports:
      - ${database_port}:5432
    environment:
      - POSTGRES_DB=${database_name}
      - POSTGRES_USER=${database_username}
      - POSTGRES_PASS=${database_password}
      - FORCE_SSL=FALSE
    restart: on-failure
    healthcheck:
      test: "PGPASSWORD=${POSTGRES_PASS} pg_isready -h 127.0.0.1 -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
