name: Build and Deploy Code
on:
  push:
    branches:
      - main
#   pull_request:
#     branches:
#       - "test_branch"
jobs:
  testApi:
    environment: testing
    env:
      DATABASE_HOSTNAME: "localhost"
      DATABASE_PORT: ${{secrets.DATABASE_PORT}}
      DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
      DATABASE_NAME: ${{secrets.DATABASE_NAME}}
      DATABASE_USERNAME: ${{secrets.DATABASE_USERNAME}}
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      ALGORITHM: ${{secrets.ALGORITHM}}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{secrets.ACCESS_TOKEN_EXPIRE_MINUTES}}
    services:
      postgres:
        image: postgres:13.2
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER}}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASS}}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB}}_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout # we find in the action marketplace
        uses: actions/checkout@v3
      - name: Install Python 3.9.4
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Install dependencies
        run: pip install -r ./src/requirements.txt
      - name: Run tests
        run: |
          pip install pytest
          pytest  -v ./src/tests || exit 1
      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.TOKEN_ACCESS_GIT}}
      - name: "Build Inventory Image"
        run: |
          docker build ./src/. --tag ghcr.io/${{github.actor}}/fastapitest:latest
          docker push ghcr.io/${{github.actor}}/fastapitest:latest
