name: Build and Deploy Code
on:
  push:
    branches:
      - main
#   pull_request:
#     branches:
#       - "test_branch"
jobs:
  jobs1:
    environment: testing
    env:
        database_hostname = ${{ secrets.DATABASE_HOSTNAME}}
        database_database_port = ${{ secrets.DATABASE_PORT}}
        database_name = ${{ secrets.DATABASE_NAME}}
        database_password = ${{ secrets.DATABASE_PASSWORD}}
        database_username = ${{ secrets.DATABASE_USERNAME}}
        algorithm = ${{ secrets.ALGORITHM}}
        access_token_expire_minutes= ${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES}}
        POSTGRES_USER = ${{ secrets.POSTGRES_USER}}
        POSTGRES_PASS =    ${{ secrets.POSTGRES_PASS}}
        POSTGRES_PORT =   ${{ secrets.POSTGRES_PORT}}
        POSTGRES_DB =  ${{ secrets.POSTGRES_DB}}

    runs-on: ubuntu-latest
    steps:
        - name: Checkout # we find in the action marketplace
          uses: actions/checkout@v2
        - name: Install Python 3.9.4
          uses: actions/setup-python@v2
          with:
            python-version: '3.9'
        - name: Update pip
          run: python -m pip install --upgrade pip
        - name: Install dependencies
          run: pip install -r ./src/requirements.txt
        - name: Run tests
          run: |
            pip install pytest
            pytest ./src/tests