# name: Docker Compose Actions Workflow #https://github.com/peter-evans/docker-compose-actions-workflow
# on: push
# jobs:
#   docker-compose-build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - name: Build the stack
#         run: docker-compose up -d
#       - name: create env file
#         run: |
#           touch ./src/app/.env
#           echo database_hostname="db" >> ./src/app/.env
#           echo  database_port=5432  >> ./src/app/.env
#           echo  database_password="hello_fastapi"   >> ./src/app/.env
#           echo  database_name="hello_fastapi_dev  >> ./src/app/.env
#           echo  database_username="hello_fastapi  >> ./src/app/.env
#           echo  secret_key = "09d25e094faa6ca2556c818145b7a9563b93f7958f6f0f4caa6cf63b88e8d3e7  >> ./src/app/.env
#           echo  algorithm="HS256  >> ./src/app/.env
#           echo  database_full_name='postgresql://hello_fastapi:hello_fastapi@db/hello_fastapi_dev  >> ./src/app/.env
#           echo  access_token_expire_minutes=30 >> ./src/app/.env
#       - name: Test
#         run: docker exec -i web  pytest -v
name: Docker Compose Action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker-compose-test:
    runs-on: ubuntu-latest
    environment: testing
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "./docker-compose-test.yml"
          up-flags: "--build"
        env:
          DATABASE_HOSTNAME: "${{secrets.DATABASE_HOSTNAME}}"
          DATABASE_PORT: ${{secrets.DATABASE_PORT}}
          DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
          DATABASE_NAME: "${{secrets.DATABASE_NAME}}"
          DATABASE_USERNAME: "${{secrets.DATABASE_USERNAME}}"
          SECRET_KEY: "${{ secrets.SECRET_KEY }}"
          ALGORITHM: "${{ secrets.ALGORITHM }}"
          ACCESS_TOKEN_EXPIRE_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}
          POSTGRES_USER: "${{ secrets.POSTGRES_USER }}"
          POSTGRES_PASSWORD: "${{ secrets.POSTGRES_PASS }}"
          POSTGRES_DB: "${{ secrets.POSTGRES_DB }}"
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}

      - name: Build and run containers
        run: |
          docker-compose -f docker-compose.yml up -d
          docker-compose -f docker-compose.yml exec web pytest -v
          docker-compose -f docker-compose-test.yml down
